package com.example.ui

import android.content.Context
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import java.util.Locale

object LanguageManager {
    // Supported languages: code -> display name
    val supportedLanguages = listOf(
        "system" to "⚙️ Sistema / Default",
        "es" to "🇪🇸 Español",
        "en" to "🇺🇸 English",
        "pt" to "🇵🇹 Português",
        "fr" to "🇫🇷 Français",
        "de" to "🇩🇪 Deutsch",
        "it" to "🇮🇹 Italiano",
        "ru" to "🇷🇺 Русский",
        "zh" to "🇨🇳 中文",
        "ja" to "🇯🇵 日本語",
        "hi" to "🇮🇳 हिन्दी",
        "ar" to "🇸🇦 العربية"
    )

    var currentLangCode by mutableStateOf("system")
        private set

    fun init(context: Context) {
        val prefs = context.getSharedPreferences("registro_pref_lang", Context.MODE_PRIVATE)
        currentLangCode = prefs.getString("selected_lang", "system") ?: "system"
    }

    fun setLanguage(context: Context, langCode: String) {
        currentLangCode = langCode
        val prefs = context.getSharedPreferences("registro_pref_lang", Context.MODE_PRIVATE)
        prefs.edit().putString("selected_lang", langCode).apply()
    }

    fun getActiveLangCode(): String {
        if (currentLangCode == "system") {
            val systemLang = Locale.getDefault().language
            val known = supportedLanguages.any { it.first == systemLang }
            return if (known) systemLang else "es" // fallback to spanish as default
        }
        return currentLangCode
    }

    // Translations Dictionary
    private val dictionary = mapOf(
        "es" to mapOf(
            "app_title" to "REGISTRO IDEA",
            "app_description" to "Configura y exporta la información de tu congregación con un solo clic",
            "tab_bitacora" to "Bitácora",
            "tab_reportes" to "Reportes",
            "tab_perfil" to "Mi Perfil",
            "search_members" to "Buscar miembros por nombre, líder, red o teléfono...",
            "all_members" to "Todos los registros",
            "new_member_btn" to "Nuevo Registro",
            "my_profile" to "Mi Perfil",
            "authorized_leader" to "Líder Autorizado",
            "edit_my_data" to "Editar mis datos",
            "save" to "Guardar",
            "cancel" to "Cancelar",
            "logout" to "Cerrar Sesión",
            "accent_color" to "Color de Acento",
            "accent_desc" to "Personaliza el color de realce de la interfaz",
            "light_mode" to "Modo Claro",
            "light_mode_desc" to "Alternar entre colores claros y oscuros",
            "sync_desc" to "Sincronizado con base de datos local y listo",
            "lang_title" to "Idioma de la Aplicación",
            "lang_desc" to "Cambia el idioma de la aplicación (al entrar coincide con el del dispositivo)",
            "rep_generator" to "Generador de Reportes",
            "rep_desc" to "Genera reportes personalizados de tu congregación para compartir o copiar",
            "rep_filters" to "⚙️ FILTROS Y CONFIGURACIÓN",
            "rep_scope" to "Ámbito del Reporte",
            "rep_total" to "Reporte Total",
            "rep_by_leader" to "Por Líder",
            "rep_select_leader" to "Selecciona el Líder",
            "rep_network" to "Filtrar por Red (Opcional)",
            "rep_all_networks" to "Todas las Redes",
            "rep_format" to "Formato de Salida",
            "rep_detallado" to "Detallado",
            "rep_estadistico" to "Estadístico",
            "rep_contactos" to "Contactos",
            "rep_gen_btn" to "GENERAR REPORTE",
            "rep_output_title" to "📋 REPORTE GENERADO EN TEXTO",
            "rep_copy" to "Copiar",
            "rep_share" to "Compartir",
            "rep_clear" to "Limpiar",
            "rep_ready_title" to "Reporte Listo para Generar",
            "rep_ready_desc" to "Filtra arriba y selecciona \"Generar Reporte\" para preparar el texto del reporte. Podrás revisarlo en el recuadro antes de copiarlo o compartirlo.",
            "login_welcome" to "Bienvenido de nuevo a",
            "login_title" to "Iniciar Sesión",
            "login_create_account" to "Crear Nueva Cuenta",
            "login_name" to "Nombre completo",
            "login_email" to "Correo Electrónico",
            "login_password" to "Contraseña",
            "login_button" to "Iniciar Sesión",
            "login_register_button" to "Registrarse",
            "login_toggle_signup" to "¿No tienes cuenta? Regístrate aquí",
            "login_toggle_signin" to "¿Ya tienes una cuenta? Inicia sesión",
            "no_leaders_found" to "No hay líderes registrados",
            "select_leader_placeholder" to "Seleccione un líder..."
        ),
        "en" to mapOf(
            "app_title" to "REGISTRO IDEA",
            "app_description" to "Configure and export your congregation's information with a single click",
            "tab_bitacora" to "Logbook",
            "tab_reportes" to "Reports",
            "tab_perfil" to "My Profile",
            "search_members" to "Search members by name, leader, network or phone...",
            "all_members" to "All records",
            "new_member_btn" to "New Record",
            "my_profile" to "My Profile",
            "authorized_leader" to "Authorized Leader",
            "edit_my_data" to "Edit my details",
            "save" to "Save",
            "cancel" to "Cancel",
            "logout" to "Log Out",
            "accent_color" to "Accent Color",
            "accent_desc" to "Customize the interface highlight color",
            "light_mode" to "Light Mode",
            "light_mode_desc" to "Toggle between light and dark colors",
            "sync_desc" to "Synced with local database and ready",
            "lang_title" to "Application Language",
            "lang_desc" to "Change display language (detects device locale at launch)",
            "rep_generator" to "Report Generator",
            "rep_desc" to "Generate custom reports of your congregation to share or copy",
            "rep_filters" to "⚙️ FILTRATION & SETTINGS",
            "rep_scope" to "Report Scope",
            "rep_total" to "Total Report",
            "rep_by_leader" to "By Leader",
            "rep_select_leader" to "Select Leader",
            "rep_network" to "Filter by Network (Optional)",
            "rep_all_networks" to "All Networks",
            "rep_format" to "Output Format",
            "rep_detallado" to "Detailed",
            "rep_estadistico" to "Statistical",
            "rep_contactos" to "Contacts",
            "rep_gen_btn" to "GENERATE REPORT",
            "rep_output_title" to "📋 GENERATED REPORT TEXT",
            "rep_copy" to "Copy",
            "rep_share" to "Share",
            "rep_clear" to "Clear",
            "rep_ready_title" to "Report Ready to Generate",
            "rep_ready_desc" to "Filter above and select \"Generate Report\" to compile report text. You can review it in the text area before copying or sharing.",
            "login_welcome" to "Welcome back to",
            "login_title" to "Sign In",
            "login_create_account" to "Create New Account",
            "login_name" to "Full Name",
            "login_email" to "Email Address",
            "login_password" to "Password",
            "login_button" to "Sign In",
            "login_register_button" to "Sign Up",
            "login_toggle_signup" to "Don't have an account? Sign up here",
            "login_toggle_signin" to "Already have an account? Sign in",
            "no_leaders_found" to "No registered leaders found",
            "select_leader_placeholder" to "Select a leader..."
        ),
        "pt" to mapOf(
            "app_title" to "REGISTRO IDEA",
            "app_description" to "Configure e exporte as informações da sua congregação com um clique",
            "tab_bitacora" to "Diário",
            "tab_reportes" to "Relatórios",
            "tab_perfil" to "Meu Perfil",
            "search_members" to "Buscar membros por nome, líder, rede ou telefone...",
            "all_members" to "Todos os registros",
            "new_member_btn" to "Novo Registro",
            "my_profile" to "Meu Perfil",
            "authorized_leader" to "Líder Autorizado",
            "edit_my_data" to "Editar meus dados",
            "save" to "Salvar",
            "cancel" to "Cancelar",
            "logout" to "Terminar Sessão",
            "accent_color" to "Cor de Destaque",
            "accent_desc" to "Personalizar a cor de realce da interface",
            "light_mode" to "Modo Claro",
            "light_mode_desc" to "Alternar entre cores claras e escuras",
            "sync_desc" to "Sincronizado com o banco de dados local",
            "lang_title" to "Idioma do Aplicativo",
            "lang_desc" to "Mude o idioma do aplicativo (detectado do dispositivo no início)",
            "rep_generator" to "Gerador de Relatórios",
            "rep_desc" to "Gere relatórios personalizados da sua congregação para compartilhar ou copiar",
            "rep_filters" to "⚙️ FILTROS E CONFIGURAÇÃO",
            "rep_scope" to "Escopo do Relatório",
            "rep_total" to "Relatório Total",
            "rep_by_leader" to "Por Líder",
            "rep_select_leader" to "Selecionar Líder",
            "rep_network" to "Filtrar por Rede (Opcional)",
            "rep_all_networks" to "Todas as Redes",
            "rep_format" to "Formato de Saída",
            "rep_detallado" to "Detalhado",
            "rep_estadistico" to "Estatístico",
            "rep_contactos" to "Contatos",
            "rep_gen_btn" to "GERAR RELATÓRIO",
            "rep_output_title" to "📋 RELATÓRIO GERADO EM TEXTO",
            "rep_copy" to "Copiar",
            "rep_share" to "Compartilhar",
            "rep_clear" to "Limpar",
            "rep_ready_title" to "Relatório Pronto para Gerar",
            "rep_ready_desc" to "Filtre acima e selecione \"Gerar Relatório\" para compilar. Você pode revisá-lo antes de copiar ou compartilhar.",
            "login_welcome" to "Bem-vindo de volta ao",
            "login_title" to "Iniciar Sessão",
            "login_create_account" to "Criar Nova Conta",
            "login_name" to "Nome completo",
            "login_email" to "E-mail",
            "login_password" to "Senha",
            "login_button" to "Entrar",
            "login_register_button" to "Cadastrar",
            "login_toggle_signup" to "Não tem conta? Cadastre-se aqui",
            "login_toggle_signin" to "Já tem conta? Iniciar sessão",
            "no_leaders_found" to "Nenhum líder cadastrado",
            "select_leader_placeholder" to "Selecione um líder..."
        ),
        "fr" to mapOf(
            "app_title" to "REGISTRO IDEA",
            "app_description" to "Configurez et exportez les informations de votre congrégation en un clic",
            "tab_bitacora" to "Registre",
            "tab_reportes" to "Rapports",
            "tab_perfil" to "Mon Profil",
            "search_members" to "Rechercher des membres par nom, leader, réseau ou téléphone...",
            "all_members" to "Tous les registres",
            "new_member_btn" to "Nouveau Registre",
            "my_profile" to "Mon Profil",
            "authorized_leader" to "Animateur Autorisé",
            "edit_my_data" to "Modifier mes informations",
            "save" to "Enregistrer",
            "cancel" to "Annuler",
            "logout" to "Se Déconnecter",
            "accent_color" to "Couleur d'accentuation",
            "accent_desc" to "Personnaliser la couleur de surbrillance de l'interface",
            "light_mode" to "Mode Clair",
            "light_mode_desc" to "Basculez entre les couleurs claires et sombres",
            "sync_desc" to "Synchronisé avec la base de données locale",
            "lang_title" to "Langue de l'application",
            "lang_desc" to "Changer la langue (détecte la langue de votre appareil)",
            "rep_generator" to "Générateur de Rapports",
            "rep_desc" to "Générez des rapports personnalisés de votre congrégation à copier ou partager",
            "rep_filters" to "⚙️ FILTRES & CONFIGURATION",
            "rep_scope" to "Portée du Rapport",
            "rep_total" to "Rapport Total",
            "rep_by_leader" to "Par Leader",
            "rep_select_leader" to "Sélectionner le Leader",
            "rep_network" to "Filtrer par Réseau (Optionnel)",
            "rep_all_networks" to "Tous les Réseaux",
            "rep_format" to "Format de Sortie",
            "rep_detallado" to "Détaillé",
            "rep_estadistico" to "Statistique",
            "rep_contactos" to "Contacts",
            "rep_gen_btn" to "GÉNÉRER LE RAPPORT",
            "rep_output_title" to "📋 RAPPORT GÉNÉRÉ EN TEXTO",
            "rep_copy" to "Copier",
            "rep_share" to "Partager",
            "rep_clear" to "Effacer",
            "rep_ready_title" to "Rapport prêt à être généré",
            "rep_ready_desc" to "Filtrez ci-dessus et sélectionnez \"Générer le rapport\". Vous pourrez le réviser ici avant de le copier ou le partager.",
            "login_welcome" to "De retour sur",
            "login_title" to "Connexion",
            "login_create_account" to "Créer un Compte",
            "login_name" to "Nom complet",
            "login_email" to "Adresse Email",
            "login_password" to "Mot de Passe",
            "login_button" to "Se Connecter",
            "login_register_button" to "S'abonner",
            "login_toggle_signup" to "Pas de compte? S'inscrire ici",
            "login_toggle_signin" to "Déjà un compte? Se connecter",
            "no_leaders_found" to "Aucun leader enregistré",
            "select_leader_placeholder" to "Sélectionnez un leader..."
         ),
         "de" to mapOf(
            "app_title" to "REGISTRO IDEA",
            "app_description" to "Gemeindeinformationen konfigurieren und exportieren mit einem Klick",
            "tab_bitacora" to "Logbuch",
            "tab_reportes" to "Berichte",
            "tab_perfil" to "Mein Profil",
            "search_members" to "Mitglieder nach Name, Leiter, Netzwerk oder Telefon suchen...",
            "all_members" to "Alle Einträge",
            "new_member_btn" to "Neuer Eintrag",
            "my_profile" to "Mein Profil",
            "authorized_leader" to "Autorisierter Leiter",
            "edit_my_data" to "Meine Daten bearbeiten",
            "save" to "Speichern",
            "cancel" to "Abbrechen",
            "logout" to "Abmelden",
            "accent_color" to "Akzentfarbe",
            "accent_desc" to "Akzentfarbe der Benutzeroberfläche anpassen",
            "light_mode" to "Heller Modus",
            "light_mode_desc" to "Zwischen hellen und dunklen Farben wechseln",
            "sync_desc" to "Mit lokaler Datenbank synchronisiert",
            "lang_title" to "App-Sprache",
            "lang_desc" to "Sprache ändern (erkennt automatisch die Gerätesprache beim Start)",
            "rep_generator" to "Berichtsgenerator",
            "rep_desc" to "Erstellen Sie benutzerdefinierte Berichte zum Teilen oder Kopieren",
            "rep_filters" to "⚙️ FILTER & EINSTELLUNGEN",
            "rep_scope" to "Berichtsumfang",
            "rep_total" to "Gesamtbericht",
            "rep_by_leader" to "Nach Leiter",
            "rep_select_leader" to "Leiter auswählen",
            "rep_network" to "Nach Netzwerk filtern (Optional)",
            "rep_all_networks" to "Alle Netzwerke",
            "rep_format" to "Ausgabeformat",
            "rep_detallado" to "Ausführlich",
            "rep_estadistico" to "Statistisch",
            "rep_contactos" to "Kontakte",
            "rep_gen_btn" to "BERICHT ERSTELLEN",
            "rep_output_title" to "📋 ERSTELLTER BERICHT",
            "rep_copy" to "Kopieren",
            "rep_share" to "Teilen",
            "rep_clear" to "Löschen",
            "rep_ready_title" to "Bericht bereit zum Erstellen",
            "rep_ready_desc" to "Filtern und wählen Sie \"Bericht erstellen\". Danach können Sie den Text überprüfen.",
            "login_welcome" to "Willkommen zurück bei",
            "login_title" to "Anmelden",
            "login_create_account" to "Konto erstellen",
            "login_name" to "Vollständiger Name",
            "login_email" to "E-Mail-Adresse",
            "login_password" to "Passwort",
            "login_button" to "Einloggen",
            "login_register_button" to "Registrieren",
            "login_toggle_signup" to "Noch kein Konto? Hier registrieren",
            "login_toggle_signin" to "Bereits ein Konto? Anmelden",
            "no_leaders_found" to "Keine registrierten Leiter gefunden",
            "select_leader_placeholder" to "Leiter auswählen..."
         ),
         "it" to mapOf(
            "app_title" to "REGISTRO IDEA",
            "app_description" to "Configura ed esporta le informazioni della tua congregazione con un clic",
            "tab_bitacora" to "Registro",
            "tab_reportes" to "Rapporti",
            "tab_perfil" to "Mio Profilo",
            "search_members" to "Cerca membri per nome, leader, rete o telefono...",
            "all_members" to "Tutti i record",
            "new_member_btn" to "Nuovo Record",
            "my_profile" to "Profilo",
            "authorized_leader" to "Leader Autorizzato",
            "edit_my_data" to "Modifica i miei dati",
            "save" to "Salva",
            "cancel" to "Annulla",
            "logout" to "Disconnetti",
            "accent_color" to "Colore di Accento",
            "accent_desc" to "Personalizza il colore principale dell'interfaccia",
            "light_mode" to "Modalità Chiara",
            "light_mode_desc" to "Passa tra colori chiari e scuri",
            "sync_desc" to "Sincronizzato con il database locale",
            "lang_title" to "Lingua dell'applicazione",
            "lang_desc" to "Cambia la lingua (rileva la lingua del dispositivo all'avvio)",
            "rep_generator" to "Generatore di Rapporti",
            "rep_desc" to "Genera rapporti personalizzati della congregazione da condividere",
            "rep_filters" to "⚙️ FILTRI E CONFIGURA",
            "rep_scope" to "Ambito del Rapporto",
            "rep_total" to "Rapporto Totale",
            "rep_by_leader" to "Per Leader",
            "rep_select_leader" to "Seleziona il Leader",
            "rep_network" to "Filtra per Rete (Opzionale)",
            "rep_all_networks" to "Tutte le Reti",
            "rep_format" to "Formato di Output",
            "rep_detallado" to "Dettagliato",
            "rep_estadistico" to "Statistico",
            "rep_contactos" to "Contatti",
            "rep_gen_btn" to "GENERA RAPPORTO",
            "rep_output_title" to "📋 RAPPORTO GENERATO",
            "rep_copy" to "Copia",
            "rep_share" to "Condividi",
            "rep_clear" to "Pulisci",
            "rep_ready_title" to "Rapporto pronto per la generazione",
            "rep_ready_desc" to "Imposta i filtri sopra e fai clic su \"Genera Rapporto\". Potrai copiarlo o condividerlo.",
            "login_welcome" to "Bentornato su",
            "login_title" to "Accedi",
            "login_create_account" to "Crea Nuovo Account",
            "login_name" to "Nome completo",
            "login_email" to "Indirizzo Email",
            "login_password" to "Password",
            "login_button" to "Accedi",
            "login_register_button" to "Registrati",
            "login_toggle_signup" to "Non hai un account? Registrati qui",
            "login_toggle_signin" to "Hai già un account? Accedi",
            "no_leaders_found" to "Nessun leader registrato",
            "select_leader_placeholder" to "Seleziona un leader..."
         ),
         "ru" to mapOf(
            "app_title" to "REGISTRO IDEA",
            "app_description" to "Настраивайте и экспортируйте информацию о вашей общине в один клик",
            "tab_bitacora" to "Журнал",
            "tab_reportes" to "Отчеты",
            "tab_perfil" to "Мой Профиль",
            "search_members" to "Поиск по имени, лидеру, сети или телефону...",
            "all_members" to "Все записи",
            "new_member_btn" to "Новая запись",
            "my_profile" to "Мой Профиль",
            "authorized_leader" to "Авторизованные Лидеры",
            "edit_my_data" to "Редактировать профиль",
            "save" to "Сохранить",
            "cancel" to "Отмена",
            "logout" to "Выйти из системы",
            "accent_color" to "Цвет акцента",
            "accent_desc" to "Настройка цвета выделения интерфейса",
            "light_mode" to "Светлая тема",
            "light_mode_desc" to "Переключение между светлыми и темными тонами",
            "sync_desc" to "Синхронизировано с локальной БД",
            "lang_title" to "Язык Приложения",
            "lang_desc" to "Изменить язык интерфейса (при входе соответствует языку устройства)",
            "rep_generator" to "Генератор Отчетов",
            "rep_desc" to "Создавайте индивидуальные отчеты для копирования или отправки",
            "rep_filters" to "⚙️ ФИЛЬТРЫ И НАСТРОЙКИ",
            "rep_scope" to "Область Отчета",
            "rep_total" to "Общий отчет",
            "rep_by_leader" to "По лидерам",
            "rep_select_leader" to "Выберите лидер",
            "rep_network" to "Фильтр по сетям (Опционально)",
            "rep_all_networks" to "Все сети",
            "rep_format" to "Формат вывода",
            "rep_detallado" to "Подробный",
            "rep_estadistico" to "Статистика",
            "rep_contactos" to "Контакты",
            "rep_gen_btn" to "ГЕНЕРИРОВАТЬ ОТЧЕТ",
            "rep_output_title" to "📋 СГЕНЕРИРОВАННЫЙ ТЕКСТ ОТЧЕТА",
            "rep_copy" to "Копировать",
            "rep_share" to "Поделиться",
            "rep_clear" to "Очистить",
            "rep_ready_title" to "Отчет готов к генерации",
            "rep_ready_desc" to "Укажите фильтры и нажмите \"Генерировать отчет\". Текст появится в поле ниже для копирования.",
            "login_welcome" to "Добро пожаловать в",
            "login_title" to "Войти",
            "login_create_account" to "Создать аккаунт",
            "login_name" to "Полное имя",
            "login_email" to "Электронная почта",
            "login_password" to "Пароль",
            "login_button" to "Войти",
            "login_register_button" to "Зарегистрироваться",
            "login_toggle_signup" to "Нет учетной записи? Зарегистрируйтесь здесь",
            "login_toggle_signin" to "Уже есть аккаунт? Войти",
            "no_leaders_found" to "Лидеры не найдены",
            "select_leader_placeholder" to "Выберите лидера..."
         ),
         "zh" to mapOf(
            "app_title" to "REGISTRO IDEA",
            "app_description" to "一键配置并导出您的教会信息",
            "tab_bitacora" to "记录本",
            "tab_reportes" to "报告",
            "tab_perfil" to "我的个人资料",
            "search_members" to "按姓名、领导者、网络或电话搜索成员...",
            "all_members" to "所有记录",
            "new_member_btn" to "新增记录",
            "my_profile" to "我的简介",
            "authorized_leader" to "授权领导者",
            "edit_my_data" to "修改资料",
            "save" to "保存",
            "cancel" to "取消",
            "logout" to "退出登录",
            "accent_color" to "主题颜色",
            "accent_desc" to "自定义界面高亮色",
            "light_mode" to "浅色模式",
            "light_mode_desc" to "在浅色和深色外观之间切换",
            "sync_desc" to "本地数据库同步就绪",
            "lang_title" to "应用语言",
            "lang_desc" to "更改应用程序语言（启动时自动匹配设备语言）",
            "rep_generator" to "报告生成器",
            "rep_desc" to "生成自定义教会报告以便分享或复制",
            "rep_filters" to "⚙️ 筛选与设置",
            "rep_scope" to "报告范围",
            "rep_total" to "完整报告",
            "rep_by_leader" to "按小组长",
            "rep_select_leader" to "选择小组长",
            "rep_network" to "按网络筛选（可选）",
            "rep_all_networks" to "所有网络",
            "rep_format" to "输出格式",
            "rep_detallado" to "详细内容",
            "rep_estadistico" to "统计信息",
            "rep_contactos" to "联系方式",
            "rep_gen_btn" to "生成报告",
            "rep_output_title" to "📋 生成的报告文本",
            "rep_copy" to "复制",
            "rep_share" to "分享",
            "rep_clear" to "清空",
            "rep_ready_title" to "报告准备就绪",
            "rep_ready_desc" to "设置上方的筛选条件，然后点击“生成报告”。您可以在下方的框中浏览并复制或分享该报告。",
            "login_welcome" to "欢迎回到",
            "login_title" to "登录",
            "login_create_account" to "创建新账户",
            "login_name" to "姓名",
            "login_email" to "电子邮件",
            "login_password" to "密码",
            "login_button" to "登录",
            "login_register_button" to "注册",
            "login_toggle_signup" to "没有账户？在这里注册",
            "login_toggle_signin" to "已经有账户了？登录",
            "no_leaders_found" to "未发现小组长",
            "select_leader_placeholder" to "选择一名领袖..."
         ),
         "ja" to mapOf(
            "app_title" to "REGISTRO IDEA",
            "app_description" to "クリック一つでグループの情報を設定およびエクスポートできます",
            "tab_bitacora" to "履歴",
            "tab_reportes" to "レポート",
            "tab_perfil" to "プロフィール",
            "search_members" to "名前、リーダー、ネットワーク、または電話番号でメンバーを検索...",
            "all_members" to "すべての記録",
            "new_member_btn" to "新規登録",
            "my_profile" to "私のプロフィール",
            "authorized_leader" to "承認されたリーダー",
            "edit_my_data" to "プロフィール編集",
            "save" to "保存",
            "cancel" to "キャンセル",
            "logout" to "ログアウト",
            "accent_color" to "アクセントカラー",
            "accent_desc" to "システムカラーのカスタマイズ",
            "light_mode" to "ライトモード",
            "light_mode_desc" to "ライトテーマとダークテーマの切り替え",
            "sync_desc" to "ローカルデータベース同期完了",
            "lang_title" to "アプリの言語",
            "lang_desc" to "言語の変更（起動時にデバイスのロケールと言語を自動検出します）",
            "rep_generator" to "レポート作成機能",
            "rep_desc" to "共有・コピー用のカスタム集計レポートを作成します",
            "rep_filters" to "⚙️ フィルター条件設定",
            "rep_scope" to "集計対象",
            "rep_total" to "総合レポート",
            "rep_by_leader" to "担当リーダー別",
            "rep_select_leader" to "リーダーを選択",
            "rep_network" to "グループ（ネットワーク）で絞り込み（任意）",
            "rep_all_networks" to "すべてのネットワーク",
            "rep_format" to "表示形式",
            "rep_detallado" to "詳細",
            "rep_estadistico" to "統計データ",
            "rep_contactos" to "連絡先一覧",
            "rep_gen_btn" to "レポートを作成",
            "rep_output_title" to "📋 出力テキストプレビュー",
            "rep_copy" to "コピーする",
            "rep_share" to "共有する",
            "rep_clear" to "クリア",
            "rep_ready_title" to "レポート作成の準備完了",
            "rep_ready_desc" to "上部の条件を設定して「レポートを作成」を押してください。生成されたレポートはここで確認できます。",
            "login_welcome" to "おかえりなさい",
            "login_title" to "ログイン",
            "login_create_account" to "アカウント作成",
            "login_name" to "氏名（フルネーム）",
            "login_email" to "メールアドレス",
            "login_password" to "パスワード",
            "login_button" to "ログイン",
            "login_register_button" to "登録する",
            "login_toggle_signup" to "アカウントをお持ちでないですか？ こちらで登録",
            "login_toggle_signin" to "既にアカウントをお持ちですか？ ログイン",
            "no_leaders_found" to "登録されたリーダーはいません",
            "select_leader_placeholder" to "リーダーを選択する..."
         ),
         "hi" to mapOf(
            "app_title" to "REGISTRO IDEA",
            "app_description" to "एक क्लिक के साथ अपनी मण्डली की जानकारी कॉन्फ़िगर और निर्यात करें",
            "tab_bitacora" to "लॉगबुक",
            "tab_reportes" to "रिपोर्ट",
            "tab_perfil" to "मेरी प्रोफाइल",
            "search_members" to "नाम, नेता, नेटवर्क या फोन द्वारा सदस्यों को खोजें...",
            "all_members" to "सभी रिकॉर्ड",
            "new_member_btn" to "नया रिकॉर्ड",
            "my_profile" to "मेरी प्रोफाइल",
            "authorized_leader" to "अधिकृत नेता",
            "edit_my_data" to "मेरी जानकारी संपादित करें",
            "save" to "सहेजें",
            "cancel" to "रद्द करें",
            "logout" to "लॉग आउट",
            "accent_color" to "एक्सेंट रंग",
            "accent_desc" to "इंटरफ़ेस के मुख्य रंग को अनुकूलित करें",
            "light_mode" to "लाइट मोड",
            "light_mode_desc" to "हल्के और गहरे रंगों के बीच स्विच करें",
            "sync_desc" to "स्थानीय डेटाबेस के साथ समन्वयित",
            "lang_title" to "आवेदन की भाषा",
            "lang_desc" to "एप्लिकेशन की भाषा बदलें (प्रवेश करते समय डिवाइस की भाषा से मेल खाता है)",
            "rep_generator" to "रिपोर्ट जनरेटर",
            "rep_desc" to "साझा या कॉपी करने के लिए अपनी मण्डली की कस्टम रिपोर्ट तैयार करें",
            "rep_filters" to "⚙️ फिल्टर और सेटिंग",
            "rep_scope" to "रिपोर्ट का दायरा",
            "rep_total" to "कुल रिपोर्ट",
            "rep_by_leader" to "नेता द्वारा",
            "rep_select_leader" to "नेता चुनें",
            "rep_network" to "नेटवर्क द्वारा फ़िल्टर करें (वैकल्पिक)",
            "rep_all_networks" to "सभी नेटवर्क",
            "rep_format" to "आउटпут प्रारूप",
            "rep_detallado" to "विस्तृत",
            "rep_estadistico" to "सांख्यिकीय",
            "rep_contactos" to "संपर्क",
            "rep_gen_btn" to "रिपोर्ट जनरेट करें",
            "rep_output_title" to "📋 जनरेट किया गया रिपोर्ट पाठ",
            "rep_copy" to "कॉपी करें",
            "rep_share" to "साझा करें",
            "rep_clear" to "साफ करें",
            "rep_ready_title" to "रिपोर्ट जनरेट करने के लिए तैयार",
            "rep_ready_desc" to "ऊपर फ़िल्टर करें और रिपोर्ट तैयार करने के लिए \"रिपोर्ट जनरेट करें\" चुनें।",
            "login_welcome" to "में आपका स्वागत है",
            "login_title" to "लॉग इन करें",
            "login_create_account" to "नया खाता बनाएं",
            "login_name" to "पूरा नाम",
            "login_email" to "ईमेल पता",
            "login_password" to "पासवर्ड",
            "login_button" to "लॉग इन करें",
            "login_register_button" to "साइन अप करें",
            "login_toggle_signup" to "खाता नहीं है? यहाँ रजिस्टर करें",
            "login_toggle_signin" to "पहले से ही खाता है? लॉगिन करें",
            "no_leaders_found" to "कोई पंजीकृत नेता नहीं मिला",
            "select_leader_placeholder" to "नेता का चयन करें..."
         ),
         "ar" to mapOf(
            "app_title" to "REGISTRO IDEA",
            "app_description" to "تكوين وتصدير معلومات كنيستك بنقرة واحدة",
            "tab_bitacora" to "السجل",
            "tab_reportes" to "التقارير",
            "tab_perfil" to "ملفي الشخصي",
            "search_members" to "البحث عن الأعضاء بالاسم أو القائد أو الشبكة أو الهاتف...",
            "all_members" to "جميع السجلات",
            "new_member_btn" to "سجل جديد",
            "my_profile" to "ملفي الشخصي",
            "authorized_leader" to "القائد المعتمد",
            "edit_my_data" to "تعديل بياناتي",
            "save" to "حفظ",
            "cancel" to "إلغاء",
            "logout" to "تسجيل الخروج",
            "accent_color" to "لون الواجهة",
            "accent_desc" to "تخصيص لون إبراز الواجهة",
            "light_mode" to "الوضع الفاتح",
            "light_mode_desc" to "التبديل بين الألوان الفاتحة والداكنة",
            "sync_desc" to "تمت المزامنة مع قاعدة البيانات المحلية",
            "lang_title" to "لغة التطبيق",
            "lang_desc" to "تغيير لغة التطبيق (تطابق لغة جهازك تلقائياً عند الدخول)",
            "rep_generator" to "منشئ التقارير",
            "rep_desc" to "توليد تقارير مخصصة لمشاركتها أو نسخها بسهولة",
            "rep_filters" to "⚙️ الفلاتر والإعدادات",
            "rep_scope" to "نطاق التقرير",
            "rep_total" to "تقرير إجمالي",
            "rep_by_leader" to "بواسطة القائد",
            "rep_select_leader" to "اختر القائد",
            "rep_network" to "تصفية حسب الشبكة (اختياري)",
            "rep_all_networks" to "جميع الشبكات",
            "rep_format" to "تنسيق الإخراج",
            "rep_detallado" to "تفصيلي",
            "rep_estadistico" to "إحصائي",
            "rep_contactos" to "جهات الاتصال",
            "rep_gen_btn" to "توليد التقرير",
            "rep_output_title" to "📋 نص التقرير الذي تم توليده",
            "rep_copy" to "نسخ",
            "rep_share" to "مشاركة",
            "rep_clear" to "مسح",
            "rep_ready_title" to "التقرير جاهز للتوليد",
            "rep_ready_desc" to "اضبط الفلاتر أعلاه واضغط على \"توليد التقرير\" لرؤية النص هنا تمهيداً لنسخه أو مشاركته.",
            "login_welcome" to "مرحباً بك مجدداً في",
            "login_title" to "تسجيل الدخول",
            "login_create_account" to "إنشاء حساب جديد",
            "login_name" to "الاسم الكامل",
            "login_email" to "البريد الإلكتروني",
            "login_password" to "كلمة المرور",
            "login_button" to "تسجيل الدخول",
            "login_register_button" to "حساب جديد",
            "login_toggle_signup" to "ليس لديك حساب؟ سجل هنا",
            "login_toggle_signin" to "لديك حساب بالفعل؟ تسجيل الدخول",
            "no_leaders_found" to "لا يوجد قادة مسجلين",
            "select_leader_placeholder" to "اختر قائداً..."
         )
    )

    fun t(key: String): String {
        val activeLang = getActiveLangCode()
        val langMap = dictionary[activeLang] ?: dictionary["es"]!!
        return langMap[key] ?: dictionary["es"]!![key] ?: key
    }
}
